# This file was generated by GoReleaser. DO NOT EDIT.
cask "portctl" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "67176212e05a08b069d5fc6058c9d4781e86302aa8df8a23fbd6dbabf3ff5918"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ca73feea7af09cec946b0529f777a49790a8af87321d18785a1846c27470aaa"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4cf23605d85541c8aba722a1f287c20d38495a2a81e5ee3f894696db5a67e483"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "560632807a29cf0bfcd07f987aca9a7e5618e45cbd40796bc78f900e9dc1c095"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "portctl"
  desc "Manage SSH tunnels and inspect local ports"
  homepage "https://github.com/oldanidavide/portctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portctl"
  bash_completion "completions/portctl.bash"
  fish_completion "completions/portctl.fish"
  zsh_completion "completions/_portctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portctl"]
    end
  end

  # No zap stanza required
end
