# This file was generated by GoReleaser. DO NOT EDIT.
cask "portctl" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "a2e61c06a0f84ca2aaa9fa688b7006a6b65d95cde5a754cc846a14128f87847a"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9efd7201ac3038e49b438c1f6f4ddef63454415167ee026ddcbea9d776636a5e"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e7fd0082c48e1a31cf32399308c161be346eabeaf61c7ae49bfd2bff9d76711e"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "009da4d4a776b5f86435c000cf321d2da1942ac7059e198f674f82dbfc187228"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "portctl"
  desc "Manage SSH tunnels and inspect local ports"
  homepage "https://github.com/oldanidavide/portctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portctl"
  bash_completion "completions/portctl.bash"
  fish_completion "completions/portctl.fish"
  zsh_completion "completions/_portctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portctl"]
    end
  end

  # No zap stanza required
end
