# This file was generated by GoReleaser. DO NOT EDIT.
cask "portctl" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "ec8f8444843bfd9a6683e0bd5c9d34c14a7938d370242c431026d333aa4557a4"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "91c2d3b67688f40c09673838e80344beb3533c9e7148a6e949b859f3a799dde8"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "349083faa5707d66aa086230c075f04cc1fedcb8d43c17441f7d0c83558ae4dc"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5fc3dbe7f5f770716ab0573bb42b66c894d109f390e93f66617eaed2376cfb95"
      url "https://github.com/oldanidavide/portctl/releases/download/v#{version}/portctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "portctl"
  desc "Manage SSH tunnels and inspect local ports"
  homepage "https://github.com/oldanidavide/portctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portctl"
  bash_completion "completions/portctl.bash"
  fish_completion "completions/portctl.fish"
  zsh_completion "completions/_portctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portctl"]
    end
  end

  # No zap stanza required
end
